### ISSUE TITLE
Support tslint.yaml files

### ISSUE THREAD

**Issue by Jancat** [Microsoft/vscode-tslint#334]
- tslint Version: 5.9.1
- typescript Version: 2.8.1

**tslint.yaml**
```yaml
extends:
  - 'tslint:latest'
  - tslint-eslint-rules
  - tslint-config-prettier
defaultSeverity: error
rulesDirectory: tslint-plugin-prettier
rules:
  prettier: true
  max-line-length:
    options:
      - 120
  no-constant-condition: true
  trailing-comma: false
  object-literal-sort-keys: false
  ordered-imports: false
  no-console: false
  no-unused-expression:
    - true
    - allow-fast-null-checks  # add this line(or any other rule) will not take effect until restart the vscode
```

**demo.ts**
```ts
function(error): void {
  // repott no-unused-expression error if not specify the `allow-fast-null-checks` option
  error && console.error(error.message)
}
 ```
Steps to Reproduce:

1. After adding the `allow-fast-null-checks` option, the error is still exists
2. Restart the vscode, the error disappear

The tslint plugin havn't take effect in time.
